# Generated by Django 2.0.4 on 2020-01-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mail_password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=10)),
                ('user_index', models.IntegerField(null=True)),
            ],
        ),
    ]
