# Generated by Django 2.0.4 on 2019-12-08 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('tel', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
                ('user_id', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Business_talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('company_id', models.IntegerField()),
                ('client_representive', models.CharField(max_length=10)),
                ('estimated_value', models.IntegerField()),
                ('completion_date', models.DateField()),
                ('stage_id', models.IntegerField()),
                ('accuracy', models.CharField(max_length=100)),
                ('next_step', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=5000)),
                ('memo1', models.CharField(max_length=2000)),
                ('memo2', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_name', models.CharField(max_length=20)),
                ('company_id', models.IntegerField()),
                ('clients_mail', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=20)),
                ('web_site_link', models.CharField(max_length=50)),
                ('sales_user_id', models.IntegerField()),
                ('stage_id', models.IntegerField()),
                ('number_of_employee', models.IntegerField()),
                ('industry', models.CharField(max_length=10)),
                ('annual_revenue', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('memo1', models.CharField(max_length=2000)),
                ('memo2', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField()),
            ],
        ),
    ]
