# Generated by Django 2.0.4 on 2020-01-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_mail_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail_password',
            name='user_index',
            field=models.IntegerField(),
        ),
    ]
