# Generated by Django 2.0.4 on 2020-01-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200101_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail_password',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
