# Generated by Django 2.0.4 on 2020-01-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200101_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business_talk_stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Client_stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=30)),
            ],
        ),
    ]
